---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: ppc64le

clone:
  disable: true

steps:
- name: greeting
  image: ubuntu:latest
  commands:
  - echo hello

trigger:
  branch:
  - main
