---
kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: ppc64le
steps:
- name: test
  image: alpine:3
  commands:
  - echo "It worked!"
  - mkdir test
  - cd test
  - arch
  - uname -r
 
