---
kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: ppc64le
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!"
  - mkdir test
  - cd test
  
- name: docker buildx
  image: docker:20
  commands:
  - docker buildx version
